---
repos:
  # Markdownlint (using David Anson's CLI)
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.9.2
    hooks:
      - id: markdownlint-cli2
        name: markdownlint
        entry: markdownlint-cli2
        language: node
        types: [markdown]
        args:
          - "--config=.markdownlint.yaml"
          - "--"
          - "**/*.md"

  # Yamllint
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        name: yamllint
        entry: yamllint
        language: system
        args:
          - "-c"
          - ".yamllint.yaml"
        types: [yaml]
